services:
  apache-benchmark-P5:
    image: mtorres26-ab-image:p5
    container_name: apache-benchmark-P5
    build:
      context: .
      dockerfile: DockerFileAB
# El siguiente comando ejecuta 100000 peticiones concurrentes de 100 en 100 al balanceador
    command:
      [
        "ab",
        "-n",
        "100000",
        "-c",
        "100",
        "https://192.168.10.50:443/"
      ]
    networks:
      red_web:
        ipv4_address: 192.168.10.60

networks:
  red_web:
    external: true
