services:
  web1:
    image: mtorres26-apache-image:p1
    container_name: web1
    build:
      context: .
      dockerfile: DockerfileApache_mtorres26
    volumes:
      - ./web_mtorres26:/var/www/html
    networks:
      red_web:
        ipv4_address: 192.168.10.2
      red_servicios:
        ipv4_address: 192.168.20.2

  web2:
    image: mtorres26-apache-image:p1
    container_name: web2
    volumes:
      - ./web_mtorres26:/var/www/html
    networks:
      red_web:
        ipv4_address: 192.168.10.3
      red_servicios:
        ipv4_address: 192.168.20.3

  web3:
    image: mtorres26-apache-image:p1
    container_name: web3
    volumes:
      - ./web_mtorres26:/var/www/html
    networks:
      red_web:
        ipv4_address: 192.168.10.4
      red_servicios:
        ipv4_address: 192.168.20.4

  web4:
    image: mtorres26-apache-image:p1
    container_name: web4
    volumes:
      - ./web_mtorres26:/var/www/html
    networks:
      red_web:
        ipv4_address: 192.168.10.5
      red_servicios:
        ipv4_address: 192.168.20.5

  web5:
    image: mtorres26-apache-image:p1
    container_name: web5
    volumes:
      - ./web_mtorres26:/var/www/html
    networks:
      red_web:
        ipv4_address: 192.168.10.6
      red_servicios:
        ipv4_address: 192.168.20.6

  web6:
    image: mtorres26-apache-image:p1
    container_name: web6
    volumes:
      - ./web_mtorres26:/var/www/html
    networks:
      red_web:
        ipv4_address: 192.168.10.7
      red_servicios:
        ipv4_address: 192.168.20.7

  web7:
    image: mtorres26-apache-image:p1
    container_name: web7
    volumes:
      - ./web_mtorres26:/var/www/html
    networks:
      red_web:
        ipv4_address: 192.168.10.8
      red_servicios:
        ipv4_address: 192.168.20.8

  web8:
    image: mtorres26-apache-image:p1
    container_name: web8
    volumes:
      - ./web_mtorres26:/var/www/html
    networks:
      red_web:
        ipv4_address: 192.168.10.9
      red_servicios:
        ipv4_address: 192.168.20.9

networks:
  red_web:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

  red_servicios:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
